version: '3.9'

services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 4200:4200
    platform: linux/x86_64
    volumes: 
      - ./frontend:/app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:4200"]
      timeout: 10s
      retries: 5
    command: ng serve --host 0.0.0.0 --poll=2000
  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/app-backend
    ports:
      - 3001:3001
    environment:
      - DB_PASS=123456
      - DB_USER=root
      - DB_NAME=dashboard
      - DB_HOST=db
      - DB_PORT=3306
      - PORT=3001
    depends_on:
      - db
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] # Caso utilize outra porta interna para o back, altere ela aqui também
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: container_db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores

networks:
  api_network:
    driver: bridge